{
 "title": "Business Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "User Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "metricName": "TotalUsers", "namespace": "NutritionApp/Business", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "metricName": "ActiveUsers", "namespace": "NutritionApp/Business", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Retention Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "metricName": "RetentionRate", "namespace": "NutritionApp/Business", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  },
  { "title": "Nutrition Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average Calories per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "metricName": "AverageCaloriesPerDay", "namespace": "NutritionApp/Business", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Average Weight Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "metricName": "AverageWeightChange", "namespace": "NutritionApp/Business", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Most Common Foods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "metricName": "CommonFood1", "namespace": "NutritionApp/Business/Foods", "region": "eu-west-1", "statistics": [ "Average" ] }
   ]
  }
 ]
}